## Table of Contents

Note to reviewers: Click on the hyperlinks below to review each part of the assignment

<div class="alert alert-block alert-info" style="margin-top: 20px">

<font size = 3>

1. <a href="#item1">Obtain Neighborhoods by Scraping</a>

2. <a href="#item2">Add Geocoding</a>

3. <a href="#item3">Explore and cluster the neighborhoods in Toronto</a>

</font>
</div>

<a id='item1'></a>
# Part 1 Obtain Neighborhoods by Scraping

In [1]:
import pandas as pd
import numpy as np

### Scrape the Neighborhood List from Wikipedia
The provided web page contains 3 tables; the one we need is the first table

In [2]:
df_raw = pd.read_html( 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M') [0]
df_raw.head()

Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront

### Clean the data
#### Remove the rows with Burough = 'Not assigned'

In [3]:
df_hoods = df_raw[ df_raw['Borough'] != 'Not assigned']
df_hoods.head()

Postcode           Borough     Neighbourhood
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights

In [4]:
# Still a problem with one row that has Neighbourhood == Not assigned
df_hoods[ df_hoods.Neighbourhood == 'Not assigned']

Postcode       Borough Neighbourhood
8      M7A  Queen's Park  Not assigned

#### Use Burough if Neighborhood == 'Not assigned'
I am doing this before combining rows with the same postal code, because if you combine the rows first (as implied by the instructions), you might get a Neighborhood like 'Not assigned, Mr. Rogers, Boondocks, ...'

In [6]:
#df.Col2 = df.Col1.where(df.Col2 == 'X', df.Col2)

df_hoods.Neighbourhood = df_hoods.Borough.where( df_hoods.Neighbourhood == 'Not assigned', df_hoods.Neighbourhood)

#Now none of the Neighbourhood values are 'Not assigned'
df_hoods[ df_hoods.Neighbourhood == 'Not assigned']

Empty DataFrame
Columns: [Postcode, Borough, Neighbourhood]
Index: []

#### Consolidate Neighborhoods from the same Postal Code

Assumptions:
* Postcode, Borough, and Neighbourhood will never be blank
* Postcode will always be a valid CA post code prefix for Toronto
* There will not be two Boroughs with the same Postcode
* There will not be two rows with the same value for Neighbourhood

In [7]:
df_post = df_hoods.groupby(['Postcode', 'Borough'],as_index=False)['Neighbourhood'].agg(','.join)
df_post.head()

Postcode      Borough                         Neighbourhood
0      M1B  Scarborough                         Rouge,Malvern
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union
2      M1E  Scarborough       Guildwood,Morningside,West Hill
3      M1G  Scarborough                                Woburn
4      M1H  Scarborough                             Cedarbrae

### Final Cell
In the last cell of your notebook, use the *.shape* method to print the number of rows of your dataframe.

In [8]:
df_post.shape

(103, 3)

<a id='item2'></a>
# Part 2 Add Geocoding

In [40]:
!pip install geocoder

Apparently, the Google geocoder is not going to work unless you have a Google Could account and an application ID. Without proper credentials, you get the **REQUEST DENIED** error shown below

In [9]:
import geocoder as geo
import requests

In [10]:
# initialize your variable to None
lat_lng_coords = None
postal_code = 'M5A'

# loop until you get the coordinates
# while(lat_lng_coords is None):
g = geo.google('{}, Toronto, Ontario'.format(postal_code))
print( g)
lat_lng_coords = g.latlng

latitude = lat_lng_coords[0]
longitude = lat_lng_coords[1]

<[REQUEST_DENIED] Google - Geocode [empty]>


TypeError: 'NoneType' object is not subscriptable

The above error is Google telling us that it won't answer unless we give a valid API key.

So we go ahead and use the provided Excel Sheet

In [11]:
df_ll = pd.read_csv('https://cocl.us/Geospatial_data')
df_ll.head()

Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [12]:
df_hoods.shape

(211, 3)

In [13]:
# Merge neighborhoods (scraped from Wikipedia) with Longitude/Latitude of each Post Code
# have to rename the Postcode column so it is the same in both data frames
df_geo = pd.merge(
    df_post, 
    df_ll.rename(columns={'Postal Code':'Postcode'}), 
    on='Postcode', how='inner')
df_geo.head()

Postcode      Borough                         Neighbourhood   Latitude  \
0      M1B  Scarborough                         Rouge,Malvern  43.806686   
1      M1C  Scarborough  Highland Creek,Rouge Hill,Port Union  43.784535   
2      M1E  Scarborough       Guildwood,Morningside,West Hill  43.763573   
3      M1G  Scarborough                                Woburn  43.770992   
4      M1H  Scarborough                             Cedarbrae  43.773136   

   Longitude  
0 -79.194353  
1 -79.160497  
2 -79.188711  
3 -79.216917  
4 -79.239476

In [14]:
df_geo.shape

(103, 5)

We still have all 103 rows that were scraped from Wikipedia. Now every row has its Longitude and Latitude.

In [16]:
#Find the neighborhoods where the Borough contains 'Toronto'
df_toronto = df_geo[df_geo.Borough.str.contains( "Toronto")].reset_index(drop=True)
df_toronto

Postcode           Borough  \
0       M4E      East Toronto   
1       M4K      East Toronto   
2       M4L      East Toronto   
3       M4M      East Toronto   
4       M4N   Central Toronto   
5       M4P   Central Toronto   
6       M4R   Central Toronto   
7       M4S   Central Toronto   
8       M4T   Central Toronto   
9       M4V   Central Toronto   
10      M4W  Downtown Toronto   
11      M4X  Downtown Toronto   
12      M4Y  Downtown Toronto   
13      M5A  Downtown Toronto   
14      M5B  Downtown Toronto   
15      M5C  Downtown Toronto   
16      M5E  Downtown Toronto   
17      M5G  Downtown Toronto   
18      M5H  Downtown Toronto   
19      M5J  Downtown Toronto   
20      M5K  Downtown Toronto   
21      M5L  Downtown Toronto   
22      M5N   Central Toronto   
23      M5P   Central Toronto   
24      M5R   Central Toronto   
25      M5S  Downtown Toronto   
26      M5T  Downtown Toronto   
27      M5V  Downtown Toronto   
28      M5W  Downtown Toronto   
29      M5X  Downtown Toronto   
30      M6G  Downtown Toronto   
31      M6H      West Toronto   
32      M6J      West Toronto   
33      M6K      West Toronto   
34      M6P      West Toronto   
35      M6R      West Toronto   
36      M6S      West Toronto   
37      M7Y      East Toronto   

                                        Neighbourhood   Latitude  Longitude  
0                                         The Beaches  43.676357 -79.293031  
1                         The Danforth West,Riverdale  43.679557 -79.352188  
2                       The Beaches West,India Bazaar  43.668999 -79.315572  
3                                     Studio District  43.659526 -79.340923  
4                                       Lawrence Park  43.728020 -79.388790  
5                                    Davisville North  43.712751 -79.390197  
6                                  North Toronto West  43.715383 -79.405678  
7                                          Davisville  43.704324 -79.388790  
8                          Moore Park,Summerhill East  43.689574 -79.383160  
9   Deer Park,Forest Hill SE,Rathnelly,South Hill,...  43.686412 -79.400049  
10                                           Rosedale  43.679563 -79.377529  
11                         Cabbagetown,St. James Town  43.667967 -79.367675  
12                               Church and Wellesley  43.665860 -79.383160  
13                           Harbourfront,Regent Park  43.654260 -79.360636  
14                            Ryerson,Garden District  43.657162 -79.378937  
15                                     St. James Town  43.651494 -79.375418  
16                                        Berczy Park  43.644771 -79.373306  
17                                 Central Bay Street  43.657952 -79.387383  
18                             Adelaide,King,Richmond  43.650571 -79.384568  
19    Harbourfront East,Toronto Islands,Union Station  43.640816 -79.381752  
20            Design Exchange,Toronto Dominion Centre  43.647177 -79.381576  
21                      Commerce Court,Victoria Hotel  43.648198 -79.379817  
22                                           Roselawn  43.711695 -79.416936  
23                 Forest Hill North,Forest Hill West  43.696948 -79.411307  
24                  The Annex,North Midtown,Yorkville  43.672710 -79.405678  
25                      Harbord,University of Toronto  43.662696 -79.400049  
26            Chinatown,Grange Park,Kensington Market  43.653206 -79.400049  
27  CN Tower,Bathurst Quay,Island airport,Harbourf...  43.628947 -79.394420  
28                    Stn A PO Boxes 25 The Esplanade  43.646435 -79.374846  
29              First Canadian Place,Underground city  43.648429 -79.382280  
30                                           Christie  43.669542 -79.422564  
31                        Dovercourt Village,Dufferin  43.669005 -79.442259  
32                            Little Portugal,Trinity  43.647927 -79.419750  
33         Brockton,Exhibition Place,Parkdale Village  43.63684

Define a function to return up to LIMIT venues from Four Square (explore endpoint)

This is the same function that was given in the lab

In [17]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [18]:
CLIENT_ID = '2DO54SC4HMRSZOCKMQQXKXAYX3XBT4VHQPHOINJBATHGLVTK' # your Foursquare ID
CLIENT_SECRET = 'CJOOZGNPVX2TSGHJF3KBEMU4222XG0IZL4U4HAMLGRVDJXN1' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version
LIMIT = 125
RADIUS = 700

In [19]:
toronto_venues = getNearbyVenues(
    names=df_toronto['Postcode'],
    latitudes=df_toronto['Latitude'],
    longitudes=df_toronto['Longitude']
)

M4E
M4K
M4L
M4M
M4N
M4P
M4R
M4S
M4T
M4V
M4W
M4X
M4Y
M5A
M5B
M5C
M5E
M5G
M5H
M5J
M5K
M5L
M5N
M5P
M5R
M5S
M5T
M5V
M5W
M5X
M6G
M6H
M6J
M6K
M6P
M6R
M6S
M7Y


In [20]:
toronto_venues.shape

(1706, 7)

In [21]:
toronto_venues.head()

Neighborhood  Neighborhood Latitude  Neighborhood Longitude  \
0          M4E              43.676357              -79.293031   
1          M4E              43.676357              -79.293031   
2          M4E              43.676357              -79.293031   
3          M4E              43.676357              -79.293031   
4          M4E              43.676357              -79.293031   

                                Venue  Venue Latitude  Venue Longitude  \
0                   Glen Manor Ravine       43.676821       -79.293942   
1  The Big Carrot Natural Food Market       43.678879       -79.297734   
2                 Grover Pub and Grub       43.679181       -79.297215   
3                 Glen Stewart Ravine       43.676300       -79.294784   
4                       Upper Beaches       43.680563       -79.292869   

         Venue Category  
0                 Trail  
1     Health Food Store  
2                   Pub  
3  Other Great Outdoors  
4          Neighborhood

In [22]:
toronto_venues.groupby('Neighborhood').count()

Neighborhood Latitude  Neighborhood Longitude  Venue  \
Neighborhood                                                         
M4E                               5                       5      5   
M4K                              41                      41     41   
M4L                              17                      17     17   
M4M                              41                      41     41   
M4N                               3                       3      3   
M4P                               9                       9      9   
M4R                              20                      20     20   
M4S                              33                      33     33   
M4T                               3                       3      3   
M4V                              15                      15     15   
M4W                               5                       5      5   
M4X                              44                      44     44   
M4Y                              89                      89     89   
M5A                              49                      49     49   
M5B                             100                     100    100   
M5C                             100                     100    100   
M5E                              56                      56     56   
M5G                              89                      89     89   
M5H                             100                     100    100   
M5J                             100                     100    100   
M5K                             100                     100    100   
M5L                             100                     100    100   
M5N                               2                       2      2   
M5P                               5                       5      5   
M5R                              24                      24     24   
M5S                              33                      33     33   
M5T                             100                     100    100   
M5V                              16                      16     16   
M5W                              96                      96     96   
M5X                             100                     100    100   
M6G                              15                      15     15   
M6H                              17                      17     17   
M6J                              64                      64     64   
M6K                              24                      24     24   
M6P                              22                      22     22   
M6R                              15                      15     15   
M6S                              37                      37     37   
M7Y                              17                      17     17   

              Venue Latitude  Venue Longitude  Venue Category  
Neighborhood                                                   
M4E                        5                5               5  
M4K                       41               41              41  
M4L                       17               17              17  
M4M                       41               41              41  
M4N                        3                3               3  
M4P                        9                9               9  
M4R                       20               20              20  
M4S                       33               33              33  
M4T                        3                3               3  
M4V                       15               15              15  
M4W                        5                5               5  
M4X                       44               44              44  
M4Y                       89               89              89  
M5A                       49               49              49  
M5B                      100              100             100  
M5C                      100              100             100  
M5E                       56               56              56

In [23]:
print('There are {} uniques categories.'.format(len(toronto_venues['Venue Category'].unique())))

There are 232 uniques categories.


<a id='item3'></a>
# Part 3 Explore and cluster the neighborhoods in Toronto
This is pretty much copy and paste from the lab
## 3. Analyze Each Neighborhood
First, build a dataframe where each venue is one-hot encoded so the columns are the venue category values, and the data contains 1 under the column of it's category

I had to change the first column from 'Neighborhood' back to 'Postcode', because there is a category with the value 'Neighborhood'

So now we end up with 234 columns -- one column for the Postcode of a venue, and 233 columns for each possible venue category.

In [24]:
# one hot encoding
toronto_onehot = pd.get_dummies(toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column (as its original title Postcode) back to dataframe
# (This is not the same way it was done in the lab, but it's simpler code)
toronto_onehot.insert(loc=0, column='Postcode', value=toronto_venues['Neighborhood'])

toronto_onehot.head()

Postcode  Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0      M4E                  0        0                   0             0   
1      M4E                  0        0                   0             0   
2      M4E                  0        0                   0             0   
3      M4E                  0        0                   0             0   
4      M4E                  0        0                   0             0   

   Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0               0                0                 0                    0   
1               0                0                 0                    0   
2               0                0                 0                    0   
3               0                0                 0                    0   
4               0                0                 0                    0   

   Antique Shop  ...  Toy / Game Store  Trail  Train Station  \
0             0  ...                 0      1              0   
1             0  ...                 0      0              0   
2             0  ...                 0      0              0   
3             0  ...                 0      0              0   
4             0  ...                 0      0              0   

   Vegetarian / Vegan Restaurant  Video Game Store  Video Store  \
0                              0                 0            0   
1                              0                 0            0   
2                              0                 0            0   
3                              0                 0            0   
4                              0                 0            0   

   Vietnamese Restaurant  Wine Bar  Wings Joint  Yoga Studio  
0                      0         0            0            0  
1                      0         0            0            0  
2                      0         0            0            0  
3                      0         0            0            0  
4                      0         0            0            0  

[5 rows x 233 columns]

Next, let's group rows by neighborhood and by taking the mean of the frequency of occurrence of each category

In [25]:
toronto_grouped = toronto_onehot.groupby('Postcode').mean().reset_index()
toronto_grouped

Postcode  Afghan Restaurant  Airport  Airport Food Court  Airport Gate  \
0       M4E           0.000000   0.0000              0.0000        0.0000   
1       M4K           0.000000   0.0000              0.0000        0.0000   
2       M4L           0.000000   0.0000              0.0000        0.0000   
3       M4M           0.000000   0.0000              0.0000        0.0000   
4       M4N           0.000000   0.0000              0.0000        0.0000   
5       M4P           0.000000   0.0000              0.0000        0.0000   
6       M4R           0.000000   0.0000              0.0000        0.0000   
7       M4S           0.000000   0.0000              0.0000        0.0000   
8       M4T           0.000000   0.0000              0.0000        0.0000   
9       M4V           0.000000   0.0000              0.0000        0.0000   
10      M4W           0.000000   0.0000              0.0000        0.0000   
11      M4X           0.000000   0.0000              0.0000        0.0000   
12      M4Y           0.011236   0.0000              0.0000        0.0000   
13      M5A           0.000000   0.0000              0.0000        0.0000   
14      M5B           0.000000   0.0000              0.0000        0.0000   
15      M5C           0.000000   0.0000              0.0000        0.0000   
16      M5E           0.000000   0.0000              0.0000        0.0000   
17      M5G           0.000000   0.0000              0.0000        0.0000   
18      M5H           0.000000   0.0000              0.0000        0.0000   
19      M5J           0.000000   0.0000              0.0000        0.0000   
20      M5K           0.000000   0.0000              0.0000        0.0000   
21      M5L           0.000000   0.0000              0.0000        0.0000   
22      M5N           0.000000   0.0000              0.0000        0.0000   
23      M5P           0.000000   0.0000              0.0000        0.0000   
24      M5R           0.000000   0.0000              0.0000        0.0000   
25      M5S           0.000000   0.0000              0.0000        0.0000   
26      M5T           0.000000   0.0000              0.0000        0.0000   
27      M5V           0.000000   0.0625              0.0625        0.0625   
28      M5W           0.000000   0.0000              0.0000        0.0000   
29      M5X           0.000000   0.0000              0.0000        0.0000   
30      M6G           0.000000   0.0000              0.0000        0.0000   
31      M6H           0.000000   0.0000              0.0000        0.0000   
32      M6J           0.000000   0.0000              0.0000        0.0000   
33      M6K           0.000000   0.0000              0.0000        0.0000   
34      M6P           0.000000   0.0000              0.0000        0.0000   
35      M6R           0.000000   0.0000              0.0000        0.0000   
36      M6S           0.000000   0.0000              0.0000        0.0000   
37      M7Y           0.000000   0.0000              0.0000        0.0000   

    Airport Lounge  Airport Service  Airport Terminal  American Restaurant  \
0            0.000            0.000             0.000             0.000000   
1            0.000            0.000             0.000             0.024390   
2            0.000            0.000             0.000             0.000000   
3            0.000            0.000             0.000             0.048780   
4            0.000            0.000             0.000             0.000000   
5            0.000            0.000             0.000             0.000000   
6            0.000            0.000             0.000             0.000000   
7            0.000            0.000             0.000             0.000000   
8            0.000            0.000             0.000             0.000000   
9            0.000            0.000             0.000             0.066667   
10           0.000            0.000             0.000             0.000000   
11           0.000            0.000             0.000          

#### Let's confirm the new size
We have one row for each of our selected post codes, one column for the value of the Postcode, and 232 columns for the categories

In [26]:
toronto_grouped.shape

(38, 233)

Let's print each neighborhood along with the top 5 most common venues

In [27]:
num_top_venues = 5

for hood in toronto_grouped['Postcode']:
    print("----"+hood+"----")
    temp = toronto_grouped[toronto_grouped.Postcode == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----M4E----
                  venue  freq
0  Other Great Outdoors   0.2
1     Health Food Store   0.2
2                   Pub   0.2
3          Neighborhood   0.2
4                 Trail   0.2


----M4K----
                    venue  freq
0        Greek Restaurant  0.22
1             Coffee Shop  0.10
2      Italian Restaurant  0.07
3          Ice Cream Shop  0.05
4  Furniture / Home Store  0.05


----M4L----
            venue  freq
0   Burrito Place  0.06
1             Gym  0.06
2  Sandwich Place  0.06
3    Burger Joint  0.06
4      Steakhouse  0.06


----M4M----
                 venue  freq
0                 Café  0.10
1          Coffee Shop  0.07
2   Italian Restaurant  0.05
3            Gastropub  0.05
4  American Restaurant  0.05


----M4N----
               venue  freq
0               Park  0.33
1           Bus Line  0.33
2        Swim School  0.33
3  Afghan Restaurant  0.00
4        Music Venue  0.00


----M4P----
               venue  freq
0  Food & Drink Shop  0.11
1           

#### Let's put that into a *pandas* dataframe
First, let's write a function to sort the venues in descending order.

In [28]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

Now let's create the new dataframe and display the top 10 venues for each neighborhood.

In [29]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Postcode']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
toronto_venues_sorted = pd.DataFrame(columns=columns)
toronto_venues_sorted['Postcode'] = toronto_grouped['Postcode']

for ind in np.arange(toronto_grouped.shape[0]):
    toronto_venues_sorted.iloc[ind, 1:] = return_most_common_venues(toronto_grouped.iloc[ind, :], num_top_venues)

toronto_venues_sorted.head()

Postcode 1st Most Common Venue 2nd Most Common Venue 3rd Most Common Venue  \
0      M4E     Health Food Store  Other Great Outdoors          Neighborhood   
1      M4K      Greek Restaurant           Coffee Shop    Italian Restaurant   
2      M4L    Italian Restaurant        Ice Cream Shop          Burger Joint   
3      M4M                  Café           Coffee Shop             Gastropub   
4      M4N                  Park           Swim School              Bus Line   

  4th Most Common Venue   5th Most Common Venue 6th Most Common Venue  \
0                   Pub                   Trail           Event Space   
1        Ice Cream Shop  Furniture / Home Store           Yoga Studio   
2         Burrito Place    Fast Food Restaurant          Liquor Store   
3    Italian Restaurant                  Bakery   American Restaurant   
4           Yoga Studio        Doner Restaurant   Filipino Restaurant   

  7th Most Common Venue 8th Most Common Venue 9th Most Common Venue  \
0  Ethiopian Restaurant     Electronics Store        Discount Store   
1           Pizza Place             Bookstore               Brewery   
2     Fish & Chips Shop        Sandwich Place            Steakhouse   
3           Yoga Studio                  Park    Seafood Restaurant   
4  Fast Food Restaurant        Farmers Market    Falafel Restaurant   

  10th Most Common Venue  
0     Falafel Restaurant  
1        Bubble Tea Shop  
2       Sushi Restaurant  
3         Sandwich Place  
4            Event Space

## 4. Cluster Neighborhoods
Run *k*-means to cluster the neighborhood into 5 clusters.

In [104]:
!pip install sklearn

In [30]:
# import k-means from clustering stage
from sklearn.cluster import KMeans

In [44]:
# set number of clusters
kclusters = 10

toronto_grouped_clustering = toronto_grouped.drop('Postcode', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=44).fit(toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_


array([9, 3, 3, 0, 5, 4, 3, 3, 7, 3, 2, 3, 3, 0, 3, 0, 0, 0, 0, 0, 0, 0,
       1, 6, 0, 0, 3, 8, 0, 0, 0, 3, 3, 0, 3, 3, 3, 3])

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

In [45]:
# add clustering labels
toronto_venues_sorted['Cluster Labels'] = kmeans.labels_
#toronto_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

toronto_merged = df_toronto

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
toronto_merged = toronto_merged.join(toronto_venues_sorted.set_index('Postcode'), on='Postcode')

toronto_merged.head() # check the last columns!

Postcode          Borough                  Neighbourhood   Latitude  \
0      M4E     East Toronto                    The Beaches  43.676357   
1      M4K     East Toronto    The Danforth West,Riverdale  43.679557   
2      M4L     East Toronto  The Beaches West,India Bazaar  43.668999   
3      M4M     East Toronto                Studio District  43.659526   
4      M4N  Central Toronto                  Lawrence Park  43.728020   

   Longitude 1st Most Common Venue 2nd Most Common Venue  \
0 -79.293031     Health Food Store  Other Great Outdoors   
1 -79.352188      Greek Restaurant           Coffee Shop   
2 -79.315572    Italian Restaurant        Ice Cream Shop   
3 -79.340923                  Café           Coffee Shop   
4 -79.388790                  Park           Swim School   

  3rd Most Common Venue 4th Most Common Venue   5th Most Common Venue  \
0          Neighborhood                   Pub                   Trail   
1    Italian Restaurant        Ice Cream Shop  Furniture / Home Store   
2          Burger Joint         Burrito Place    Fast Food Restaurant   
3             Gastropub    Italian Restaurant                  Bakery   
4              Bus Line           Yoga Studio        Doner Restaurant   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0           Event Space  Ethiopian Restaurant     Electronics Store   
1           Yoga Studio           Pizza Place             Bookstore   
2          Liquor Store     Fish & Chips Shop        Sandwich Place   
3   American Restaurant           Yoga Studio                  Park   
4   Filipino Restaurant  Fast Food Restaurant        Farmers Market   

  9th Most Common Venue 10th Most Common Venue  Cluster Labels  
0        Discount Store     Falafel Restaurant               9  
1               Brewery        Bubble Tea Shop               3  
2            Steakhouse       Sushi Restaurant               3  
3    Seafood Restaurant         Sandwich Place               0  
4    Falafel Restaurant            Event Space               5

I noticed that the clustering algorithm picked clusters that contained only 1 or 2 data points. So most zones fell into a single cluster, but the following 5 zones were put into their own clusters.

In [46]:
toronto_merged[toronto_merged['Cluster Labels'] != 9]

Postcode           Borough  \
1       M4K      East Toronto   
2       M4L      East Toronto   
3       M4M      East Toronto   
4       M4N   Central Toronto   
5       M4P   Central Toronto   
6       M4R   Central Toronto   
7       M4S   Central Toronto   
8       M4T   Central Toronto   
9       M4V   Central Toronto   
10      M4W  Downtown Toronto   
11      M4X  Downtown Toronto   
12      M4Y  Downtown Toronto   
13      M5A  Downtown Toronto   
14      M5B  Downtown Toronto   
15      M5C  Downtown Toronto   
16      M5E  Downtown Toronto   
17      M5G  Downtown Toronto   
18      M5H  Downtown Toronto   
19      M5J  Downtown Toronto   
20      M5K  Downtown Toronto   
21      M5L  Downtown Toronto   
22      M5N   Central Toronto   
23      M5P   Central Toronto   
24      M5R   Central Toronto   
25      M5S  Downtown Toronto   
26      M5T  Downtown Toronto   
27      M5V  Downtown Toronto   
28      M5W  Downtown Toronto   
29      M5X  Downtown Toronto   
30      M6G  Downtown Toronto   
31      M6H      West Toronto   
32      M6J      West Toronto   
33      M6K      West Toronto   
34      M6P      West Toronto   
35      M6R      West Toronto   
36      M6S      West Toronto   
37      M7Y      East Toronto   

                                        Neighbourhood   Latitude  Longitude  \
1                         The Danforth West,Riverdale  43.679557 -79.352188   
2                       The Beaches West,India Bazaar  43.668999 -79.315572   
3                                     Studio District  43.659526 -79.340923   
4                                       Lawrence Park  43.728020 -79.388790   
5                                    Davisville North  43.712751 -79.390197   
6                                  North Toronto West  43.715383 -79.405678   
7                                          Davisville  43.704324 -79.388790   
8                          Moore Park,Summerhill East  43.689574 -79.383160   
9   Deer Park,Forest Hill SE,Rathnelly,South Hill,...  43.686412 -79.400049   
10                                           Rosedale  43.679563 -79.377529   
11                         Cabbagetown,St. James Town  43.667967 -79.367675   
12                               Church and Wellesley  43.665860 -79.383160   
13                           Harbourfront,Regent Park  43.654260 -79.360636   
14                            Ryerson,Garden District  43.657162 -79.378937   
15                                     St. James Town  43.651494 -79.375418   
16                                        Berczy Park  43.644771 -79.373306   
17                                 Central Bay Street  43.657952 -79.387383   
18                             Adelaide,King,Richmond  43.650571 -79.384568   
19    Harbourfront East,Toronto Islands,Union Station  43.640816 -79.381752   
20            Design Exchange,Toronto Dominion Centre  43.647177 -79.381576   
21                      Commerce Court,Victoria Hotel  43.648198 -79.379817   
22                                           Roselawn  43.711695 -79.416936   
23                 Forest Hill North,Forest Hill West  43.696948 -79.411307   
24                  The Annex,North Midtown,Yorkville  43.672710 -79.405678   
25                      Harbord,University of Toronto  43.662696 -79.400049   
26            Chinatown,Grange Park,Kensington Market  43.653206 -79.400049   
27  CN Tower,Bathurst Quay,Island airport,Harbourf...  43.628947 -79.394420   
28                    Stn A PO Boxes 25 The Esplanade  43.646435 -79.374846   
29              First Canadian Place,Underground city  43.648429 -79.382280   
30                                           Christie  43.669542 -79.422564   
31                        Dovercourt Village,Dufferin  43.669005 -79.442259   
32                            Little Portugal,Trinity  43.647927 -79.419750   
33         Brockton,Exhibition Place,Parkdale Village  43.636847 -79.428191   
34                       High Park,The Junction South  43.6616

In [47]:
import folium
import matplotlib.cm as cm
import matplotlib.colors as colors
from IPython.display import Markdown, display, HTML

In [48]:
# create map
latitude = 43.6532
longitude = -79.3832
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(toronto_merged['Latitude'], toronto_merged['Longitude'], toronto_merged['Postcode'], toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)

# HTML(m._repr_html_())
HTML(map_clusters._repr_html_())

Since Folium maps will not show in Github, I took a screen shot of the map and pasted the image into this markdown cell


## 5. Examine Clusters

Now, you can examine each cluster and determine the discriminating venue categories that distinguish each cluster. Based on the defining categories, you can then assign a name to each cluster

In [49]:
# This loop shows the zones for each cluster, which is an improvement from the code in the lab
# (where each zone was displayed with an separate line of code)
for c in range(kclusters):
    display( Markdown('**Cluster ' + str(c) + '**'))
    display( toronto_merged.loc[toronto_merged['Cluster Labels'] == c, toronto_merged.columns[[1] + list(range(5, toronto_merged.shape[1]))]])


**Cluster 0**

Borough 1st Most Common Venue 2nd Most Common Venue  \
3       East Toronto                  Café           Coffee Shop   
13  Downtown Toronto           Coffee Shop                  Park   
15  Downtown Toronto           Coffee Shop                 Hotel   
16  Downtown Toronto           Coffee Shop          Cocktail Bar   
17  Downtown Toronto           Coffee Shop    Italian Restaurant   
18  Downtown Toronto           Coffee Shop                  Café   
19  Downtown Toronto           Coffee Shop              Aquarium   
20  Downtown Toronto           Coffee Shop                  Café   
21  Downtown Toronto           Coffee Shop                  Café   
24   Central Toronto           Coffee Shop        Sandwich Place   
25  Downtown Toronto                  Café            Restaurant   
28  Downtown Toronto           Coffee Shop            Restaurant   
29  Downtown Toronto           Coffee Shop                  Café   
30  Downtown Toronto         Grocery Store                  Café   
33      West Toronto           Coffee Shop        Breakfast Spot   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
3              Gastropub    Italian Restaurant                Bakery   
13                  Café                Bakery  Gym / Fitness Center   
15            Restaurant                  Café    Italian Restaurant   
16              Beer Bar                  Café            Steakhouse   
17        Sandwich Place        Ice Cream Shop                  Café   
18                   Bar            Steakhouse       Thai Restaurant   
19                 Hotel                  Café    Italian Restaurant   
20                 Hotel    Italian Restaurant            Restaurant   
21                 Hotel            Restaurant   American Restaurant   
24                  Café           Pizza Place        History Museum   
25   Japanese Restaurant                   Bar             Bookstore   
28                  Café    Seafood Restaurant          Cocktail Bar   
29            Steakhouse                 Hotel            Restaurant   
30                  Park                 Diner             Nightclub   
33                  Café                Office         Burrito Place   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
3    American Restaurant           Yoga Studio                  Park   
13               Theater    Mexican Restaurant                   Pub   
15                Bakery              Beer Bar        Breakfast Spot   
16                Bakery    Seafood Restaurant        Farmers Market   
17          Burger Joint       Bubble Tea Shop                   Spa   
18      Asian Restaurant            Restaurant        Cosmetics Shop   
19               Brewery                Bakery   Sporting Goods Shop   
20                   Bar   American Restaurant                   Gym   
21    Seafood Restaurant         Deli / Bodega                Bakery   
24             BBQ Joint     Indian Restaurant     Jewish Restaurant   
25                Bakery          Dessert Shop         Poutine Place   
28  Fast Food Restaurant              Beer Bar                 Hotel   
29                   Gym                   Bar             Gastropub   
30            Baby Store    Italian Restaurant            Restaurant   
33  Caribbean Restaurant               Stadium            Restaurant   

   9th Most Common Venue 10th Most Common Venue  Cluster Labels  
3     Seafood Restaurant         Sandwich Place               0  
13            Restaurant         Breakfast Spot               0  
15             Gastropub           Cocktail Bar               0  
16           Cheese Shop              Irish Pub               0  
17      Sushi Restaurant                    Bar               0  
18                 Hotel           Burger Joint               0  
19           Pizza Place         Scenic Lookout               0  
20             Gastropub          Deli / Bodega               0  
21            Steakhouse

**Cluster 1**

Borough 1st Most Common Venue 2nd Most Common Venue  \
22  Central Toronto           Music Venue                Garden   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
22           Yoga Studio  Fast Food Restaurant        Farmers Market   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
22    Falafel Restaurant           Event Space  Ethiopian Restaurant   

   9th Most Common Venue       10th Most Common Venue  Cluster Labels  
22     Electronics Store  Eastern European Restaurant               1

**Cluster 2**

Borough 1st Most Common Venue 2nd Most Common Venue  \
10  Downtown Toronto                  Park            Playground   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
10                 Trail              Building           Yoga Studio   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
10              Dive Bar        Farmers Market    Falafel Restaurant   

   9th Most Common Venue 10th Most Common Venue  Cluster Labels  
10           Event Space   Ethiopian Restaurant               2

**Cluster 3**

Borough 1st Most Common Venue          2nd Most Common Venue  \
1       East Toronto      Greek Restaurant                    Coffee Shop   
2       East Toronto    Italian Restaurant                 Ice Cream Shop   
6    Central Toronto           Coffee Shop                 Clothing Store   
7    Central Toronto        Sandwich Place                   Dessert Shop   
9    Central Toronto                   Pub                    Coffee Shop   
11  Downtown Toronto           Coffee Shop                    Pizza Place   
12  Downtown Toronto           Coffee Shop            Japanese Restaurant   
14  Downtown Toronto           Coffee Shop                 Clothing Store   
26  Downtown Toronto                  Café  Vegetarian / Vegan Restaurant   
31      West Toronto              Pharmacy                    Supermarket   
32      West Toronto                   Bar                    Coffee Shop   
34      West Toronto                  Café             Mexican Restaurant   
35      West Toronto        Breakfast Spot                      Gift Shop   
36      West Toronto                  Café                    Coffee Shop   
37      East Toronto    Light Rail Station                    Pizza Place   

    3rd Most Common Venue 4th Most Common Venue        5th Most Common Venue  \
1      Italian Restaurant        Ice Cream Shop       Furniture / Home Store   
2            Burger Joint         Burrito Place         Fast Food Restaurant   
6             Yoga Studio   Sporting Goods Shop       Furniture / Home Store   
7                    Café    Italian Restaurant                     Pharmacy   
9      Light Rail Station          Liquor Store                   Sports Bar   
11                 Bakery                  Café                   Restaurant   
12                Gay Bar      Sushi Restaurant                   Restaurant   
14         Cosmetics Shop  Fast Food Restaurant                         Café   
26  Vietnamese Restaurant    Chinese Restaurant           Mexican Restaurant   
31                 Bakery          Liquor Store                  Music Venue   
32       Asian Restaurant          Cocktail Bar                  Men's Store   
34                    Bar             Bookstore           Italian Restaurant   
35              Bookstore          Dessert Shop  Eastern European Restaurant   
36            Pizza Place      Sushi Restaurant           Italian Restaurant   
37          Auto Workshop         Garden Center                       Garden   

   6th Most Common Venue  7th Most Common Venue      8th Most Common Venue  \
1            Yoga Studio            Pizza Place                  Bookstore   
2           Liquor Store      Fish & Chips Shop             Sandwich Place   
6   Fast Food Restaurant     Mexican Restaurant         Miscellaneous Shop   
7            Pizza Place            Coffee Shop           Sushi Restaurant   
9             Restaurant            Supermarket           Sushi Restaurant   
11    Chinese Restaurant                    Pub         Italian Restaurant   
12                   Pub            Men's Store   Mediterranean Restaurant   
14             Bookstore    Japanese Restaurant                 Restaurant   
26   Dumpling Restaurant                    Bar                     Bakery   
31                  Park                   Café  Middle Eastern Restaurant   
32              Boutique  Vietnamese Restaurant                 Restaurant   
34           Music Venue                  Diner  Cajun / Creole Restaurant   
35                   Bar                   Bank              Movie Theater   
36             Bookstore               Pharmacy               Dessert Shop   
37  Fast Food Restaurant         Farmers Market              Moving Target   

   9th Most Common Venue 10th Most Common Venue  Cluster Labels  
1                Brewery        Bubble Tea Shop               3  
2             Steakhouse       Sushi Restaurant               3  
6                  Diner           Dessert Shop     

**Cluster 4**

Borough 1st Most Common Venue 2nd Most Common Venue  \
5  Central Toronto        Breakfast Spot         Grocery Store   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
5     Food & Drink Shop        Clothing Store          Dance Studio   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
5        Sandwich Place                 Hotel                   Gym   

  9th Most Common Venue 10th Most Common Venue  Cluster Labels  
5                  Park     Falafel Restaurant               4

**Cluster 5**

Borough 1st Most Common Venue 2nd Most Common Venue  \
4  Central Toronto                  Park           Swim School   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
4              Bus Line           Yoga Studio      Doner Restaurant   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
4   Filipino Restaurant  Fast Food Restaurant        Farmers Market   

  9th Most Common Venue 10th Most Common Venue  Cluster Labels  
4    Falafel Restaurant            Event Space               5

**Cluster 6**

Borough 1st Most Common Venue 2nd Most Common Venue  \
23  Central Toronto                  Park                 Trail   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
23              Bus Line      Sushi Restaurant         Jewelry Store   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
23           Yoga Studio      Doner Restaurant  Fast Food Restaurant   

   9th Most Common Venue 10th Most Common Venue  Cluster Labels  
23        Farmers Market     Falafel Restaurant               6

**Cluster 7**

Borough 1st Most Common Venue 2nd Most Common Venue  \
8  Central Toronto            Playground                  Park   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
8            Restaurant           Yoga Studio        Discount Store   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
8        Farmers Market    Falafel Restaurant           Event Space   

  9th Most Common Venue 10th Most Common Venue  Cluster Labels  
8  Ethiopian Restaurant      Electronics Store               7

**Cluster 8**

Borough 1st Most Common Venue 2nd Most Common Venue  \
27  Downtown Toronto        Airport Lounge       Airport Service   

   3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
27      Airport Terminal                 Plane       Harbor / Marina   

   6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
27      Sculpture Garden              Boutique         Boat or Ferry   

   9th Most Common Venue 10th Most Common Venue  Cluster Labels  
27                   Bar            Coffee Shop               8

**Cluster 9**

Borough 1st Most Common Venue 2nd Most Common Venue  \
0  East Toronto     Health Food Store  Other Great Outdoors   

  3rd Most Common Venue 4th Most Common Venue 5th Most Common Venue  \
0          Neighborhood                   Pub                 Trail   

  6th Most Common Venue 7th Most Common Venue 8th Most Common Venue  \
0           Event Space  Ethiopian Restaurant     Electronics Store   

  9th Most Common Venue 10th Most Common Venue  Cluster Labels  
0        Discount Store     Falafel Restaurant               9

#### Analysis
Mostly, the clustering algorithm seems to pick outliers. So most of the clusters have only a single neighborhood or zone. I ran this experiment dozens of times, and I almost always got each cluster except one to have only a single zone. For example, the airport (Cluster 8) always seems to be in its own cluster.

When I increased the value of K to be high enough to weed out the outliers, the algorithm split the zones into two roughly equal clusters (which appear as Cluster 0 and Cluster 3 above). This was not always consistent, but it seems that if I use a value of K around 10, you can start to see the split into two clusters each with more than one or 2 neighborhoods. 

If you look at the map, you can see that the algorithm seems to be differentiating between downtown and the outer parts of Toronto (still called Toronto, so not proper suburbs).